name: docker-publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CLOUDSMITH_USERNAME }}
          password: ${{ secrets.CLOUDSMITH_KEY }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: docker.cloudsmith.io/gregmus-co/poll-play/{name}:latest